name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    AZURE_SWA_NAME: "swa-competence-test" # set this to your swa name on Azure
    AZURE_SWA_RESOURCE_GROUP: "rg-competence-test" # set this to your resource group name on Azure
    APP_LOCATION: "/" # location of your client code
    API_LOCATION: "api" # location of your api source code - optional
    OUTPUT_LOCATION: "build" # location of client code build output

permissions:
    id-token: write
    contents: read

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            - name: Az CLI login
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  enable-AzPSSession: true
            - name: Get deployment key
              id: deploymentkey
              uses: azure/powershell@v1
              with:
                  inlineScript: |
                      $secretInfo = $(az staticwebapp secrets list --name ${{ env.AZURE_SWA_NAME }} -g ${{ env.AZURE_SWA_RESOURCE_GROUP }}) | ConvertFrom-JSON
                      $deploymentKey = $secretInfo.properties.apiKey
                      "deploymentkey=$deploymentKey" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                  azPsVersion: latest

            - uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
              with:
                  azure_static_web_apps_api_token: ${{ steps.deploymentkey.outputs.deploymentkey }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: "upload"
                  app_location: ${{ env.APP_LOCATION }}
                  api_location: ${{ env.API_LOCATION }}
                  output_location: ${{ env.OUTPUT_LOCATION }}
            - name: Reset deployment key
              uses: azure/powershell@v1
              with:
                  inlineScript: |
                      $secretInfo = Reset-AzStaticWebAppApiKey -Name ${{ env.AZURE_SWA_NAME }} -ResourceGroup ${{ env.AZURE_SWA_RESOURCE_GROUP }}
                      $secretInfo = ""
                  azPsVersion: latest

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ steps.deploymentkey.outputs.deploymentkey }}
                  action: "close"
